### ISSUE TITLE
CMakeLists

### ISSUE THREAD

**Issue by untereiner** [bparolin/animation#2]
Voici un diff de quelques corrections que j'ai apporté à tes CMakeLists
[patch.txt](https://github.com/bparolin/animation/files/1457657/patch.txt)

**Comment by bparolin** [comment]
Merci du retour, j'ai fait les modifications mais quand j'enlève le "add_subdirectory(examples)" QtCreator ne prend plus en compte le dossier et donc ne veut plus compiler particles_main.cpp

**Comment by untereiner** [comment]
est-ce que tu as refait un ccmake ou cmake-gui ? C'est le CMakeLists principal à la racine de cgogn qui cherche le dossier "example" dans les module. Il n'y a pas besoin de ce `add_subdirectory`

**Comment by bparolin** [comment]
Ah oui c'est mieux, le flag pour build les exemples était pas activé.
